from PyQt5 import QtCore
from PyQt5 import QtGui
from PyQt5 import QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowTitle("Crypto-search")
        MainWindow.setFixedSize(800, 500)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.SearchButton = QtWidgets.QPushButton(self.centralwidget)
        self.SearchButton.setGeometry(QtCore.QRect(320, 420, 191, 61))
        self.SearchButton.setIconSize(QtCore.QSize(22, 22))
        self.SearchButton.setFlat(False)
        self.SearchButton.setObjectName("SearchButton")
        self.ChooseCurrency = QtWidgets.QComboBox(self.centralwidget)
        self.ChooseCurrency.setGeometry(QtCore.QRect(690, 40, 91, 22))
        self.ChooseCurrency.setObjectName("ChooseCurrency")
        self.ChooseCurrency.addItem("USD")
        self.ChooseCurrency.addItem("PLN")
        self.ChooseCurrency.addItem("EUR")
        self.ChooseCurrency.addItem("GBP")
        self.ChooseCurrency.addItem("JPY")
        self.ChooseCurrency.addItem("RUB")
        self.ChooseCurrency.addItem("CNY")
        self.ChooseCurrency.addItem("KRW")
        self.ChooseCurrency.addItem("CZK")
        self.ChooseCurrency.addItem("CHF")
        self.GraphLabel = QtWidgets.QLabel(self.centralwidget)
        self.GraphLabel.setGeometry(QtCore.QRect(40, 420, 130, 30))
        self.GraphLabel.setObjectName("GraphLabel")
        self.ChooseGraph = QtWidgets.QComboBox(self.centralwidget)
        self.ChooseGraph.setGeometry(QtCore.QRect(30, 450, 130, 30))
        self.ChooseGraph.setObjectName("ChooseGraph")
        self.ChooseGraph.addItem("Approximate")
        self.ChooseGraph.addItem("High")
        self.ChooseGraph.addItem("Low")
        self.SearchLabel = QtWidgets.QLabel(self.centralwidget)
        self.SearchLabel.setGeometry(QtCore.QRect(350, 10, 151, 21))
        self.SearchLabel.setObjectName("SearchLabel")
        self.CurrencyLabel = QtWidgets.QLabel(self.centralwidget)
        self.CurrencyLabel.setGeometry(QtCore.QRect(690, 10, 91, 20))
        self.CurrencyLabel.setObjectName("CurrencyLabel")
        self.DayRange = QtWidgets.QSlider(self.centralwidget)
        self.DayRange.setGeometry(QtCore.QRect(20, 40, 160, 22))
        self.DayRange.setMinimum(1)
        self.DayRange.setMaximum(30)
        self.DayRange.setProperty("value", 14)
        self.DayRange.setOrientation(QtCore.Qt.Horizontal)
        self.DayRange.setObjectName("DayRange")
        self.DaysLabel = QtWidgets.QLabel(self.centralwidget)
        self.DaysLabel.setGeometry(QtCore.QRect(10, 10, 191, 16))
        self.DaysLabel.setObjectName("DaysLabel")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(450, 90, 340, 311))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setMaximumSize(QtCore.QSize(350, 16777215))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.LimitInfo = QtWidgets.QTextBrowser(self.centralwidget)
        self.LimitInfo.setGeometry(QtCore.QRect(200, 30, 40, 40))
        self.LimitInfo.setObjectName("LimitInfo")
        self.LimitInfo.setStyleSheet("font: 15pt")
        self.LimitInfo.setText("14")
        self.VolumeIn = QtWidgets.QTextBrowser(self.centralwidget)
        self.VolumeIn.setGeometry(QtCore.QRect(550, 430, 240, 41))
        self.VolumeIn.setObjectName("VolumeIn")
        self.VolumeIn.setStyleSheet("font: 15pt")
        self.VolumeLabel = QtWidgets.QLabel(self.centralwidget)
        self.VolumeLabel.setGeometry(QtCore.QRect(650, 400, 101, 31))
        self.VolumeLabel.setObjectName("VolumeLabel")
        self.CryptoInput = QtWidgets.QTextEdit(self.centralwidget)
        self.CryptoInput.setGeometry(QtCore.QRect(290, 40, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.CryptoInput.setFont(font)
        self.CryptoInput.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.CryptoInput.setUndoRedoEnabled(True)
        self.CryptoInput.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.CryptoInput.setAlignment(QtCore.Qt.AlignCenter)
        self.CryptoInput.setObjectName("CryptoInput")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.msg = QtWidgets.QMessageBox()
        self.msg.setIcon(QtWidgets.QMessageBox.Information)
        self.msg.setText("Wrong Crypto Name")
        self.msg.setInformativeText("Please insert short name for choosen CrypoCurrency. Default BTC was set")
        self.msg.setWindowTitle("Try again")
        self.pic = QtWidgets.QLabel(self.centralwidget)
        self.pic.move(10, 90)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.SearchButton.setText(_translate("MainWindow", "Update"))
        self.ChooseCurrency.setItemText(0, _translate("MainWindow", "USD"))
        self.ChooseCurrency.setItemText(1, _translate("MainWindow", "PLN"))
        self.ChooseCurrency.setItemText(2, _translate("MainWindow", "EUR"))
        self.GraphLabel.setText(_translate("MainWindow", "Choose Graph Type"))
        self.SearchLabel.setText(_translate("MainWindow", "Search for CryptoCurrency"))
        self.CurrencyLabel.setText(_translate("MainWindow", "Choose Currency"))
        self.DaysLabel.setText(_translate("MainWindow", "Choose Days History (up to a month)"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Date"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "High"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Low"))
        self.VolumeIn.setPlaceholderText(_translate("MainWindow", "--"))
        self.VolumeLabel.setText(_translate("MainWindow", "Market Volume"))
        self.CryptoInput.setText(_translate("MainWindow", "BTC"))
        self.CryptoInput.setAlignment(QtCore.Qt.AlignCenter)


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
